language: python
install:
  - pip install yamllint
jobs:
  include:
    - stage: check_poc
      script: 
        - git remote set-branches --add origin master
        - git fetch
        - wget https://github.com/chaitin/xray/releases/download/0.16.3/xray_linux_amd64.zip
        - unzip xray_linux_amd64.zip
        - ./xray_linux_amd64 poclint --poc "./pocs/*" --rules filename,filepath,yamlschema,yamllint,cellint